services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend

    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=localhost
      - SERVER_READ_TIMEOUT=30s
      - SERVER_WRITE_TIMEOUT=30s
      - DATA_FOLDER=./data/portfolio.toml
    volumes:
      - ./backend/data:/root/data
    restart: unless-stopped
    networks:
      - portfolio-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    ports:
      - "${INTERNAL_IP}:3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - portfolio-network



networks:
  portfolio-network:
    name: portfolio-network
